### ISSUE TITLE
Error message: "Request of type 'wallet_addEthereumChain' already pending for origin https://app.arablefi.com. Please wait"

### ISSUE THREAD

**Issue by manjash** [ArableProtocol/bugs#5]
Steps to reproduce:
1. Have metamask extension set up in ETH
2. Open https://app.arablefi.com/
3. See message "Looks like you are on the wrong network...", CTA "Switch network"
<img width="518" alt="image" src="https://user-images.githubusercontent.com/11697165/147889109-55ef9dbf-1532-425e-9f4c-4c788c47658e.png">
4. Press "Switch network"
5. Extension popup opens
6. Leave it, don't close
7. Go back to https://app.arablefi.com/
8. Press CTA "Switch network" again
9. See code -32002 error
`{"code":-32002,"message":"Request of type 'wallet_addEthereumChain' already pending for origin https://app.arablefi.com. Please wait.","stack":"{\n  \"code\": -32002,\n  \"message\": \"Request of type 'wallet_addEthereumChain' already pending for origin https://app.arablefi.com. Please wait.\",\n  \"stack\": \"Error: Request of type 'wallet_addEthereumChain' already pending for origin https://app.arablefi.com. Please wait.\\n    at new i (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-0.js:18:148782)\\n    at s (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-0.js:18:146325)\\n    at Object.resourceUnavailable (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-0.js:18:147393)\\n    at c._add (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-1.js:1:200253)\\n    at c.addAndShowApprovalRequest (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-1.js:1:198515)\\n    at implementation (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-2.js:7:320204)\"\n}\n  at new i (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-0.js:18:148782)\n  at s (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-0.js:18:146325)\n  at Object.resourceUnavailable (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-0.js:18:147393)\n  at c._add (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-1.js:1:200253)\n  at c.addAndShowApprovalRequest (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-1.js:1:198515)\n  at implementation (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-2.js:7:320204)"}`
<img width="453" alt="image" src="https://user-images.githubusercontent.com/11697165/147889167-e9d82a88-11cf-458a-916b-62084219deca.png">

Expected:
1. Either switch to the extension popup that's already open
2. Or give a human friendly message in the website interface instead of the still opened popup "Looks like you are on the wrong network...", CTA "Switch network"

**Comment by liccampanavd** [comment]
@gophereth I cant reproduce it, I never see that error message when I click again on CTA "Switch network"...
Do you can reproduce it?

**Comment by gophereth** [comment]
@liccampanavd  You can work on other tickets if you can't reproduce the issue.

**Comment by manjash** [comment]
I think Avalance Fuji testnet wasn't added to my Metamask when I reported the issue. After that I added it from the chainlist.org, and the metamask stopped showing warnings and the issue doesn't occur anymore. 
If you want to reproduce the issue, I'd try with a new browser/metamask extension (but maybe the issue is not that high in priority).
